name: "coverage"
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install

            - name: Run test coverage
              run: npm test

            - name: Coverage report
              uses: eleboys/test-coverage-report-action@v1.0.2
              id: report
              with:
                path: coverage/coverage-final.json
                title: Karma Test Coverage
